In [1]:
import numpy as np
from scipy.linalg import solve, lstsq

### 1

In [2]:
i,j,k = [1,0,0],[0,1,0],[0,0,1]
I = np.array([i,j,k])
b = np.array([2,3,4])

print(I)
x = solve(I,b)
print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[2. 3. 4.]


### 2

In [3]:
d1,d2,d3 = [2,0,0],[0,3,0],[0,0,4]
D = np.array([d1,d2,d3])
B = np.array([4,9,16])

print(D)
X = solve(D,B)
print(X)

[[2 0 0]
 [0 3 0]
 [0 0 4]]
[2. 3. 4.]


### 4

In [4]:
a1,a2,a3 = [1,1,3],[1,-1,1],[0,0,1]
A = np.array([a1,a2,a3])
b = np.array([6,4,2])

x1 = solve(A,b)
print(x1)

b[2] = 0
x2 = solve(A,b)
print(x2)

x_mid = (x1+x2)/2
print(x_mid)

[ 1. -1.  2.]
[5. 1. 0.]
[3. 0. 1.]


### 5

In [5]:
a1,a2,a3 = [1,1,1],[1,2,1],[2,3,2]
A = np.array([a1,a2,a3])
b = np.array([2,3,5])

## linalg.solve can't handle singular matrix
## x = solve(A,b)
x = lstsq(A,b)

print(x[0])

[0.5 1.  0.5]


### 6

In [6]:
a1,a2,a3 = [1,1,1],[1,2,1],[2,3,2]
A = np.array([a1,a2,a3])
b = np.array([2,3,9])

# gives inproper results, it has no soluti
x = lstsq(A,b)
print(x)

(array([1.16666667, 1.        , 1.16666667]), array([], dtype=float64), 2, array([5.07613488e+00, 4.82550169e-01, 2.69573835e-16]))


### 7

In [10]:
# a
A = np.array([[1,2,4],[-2,3,1],[-4,1,2]])
x = np.array([2,2,3])

b = A.dot(x)
print(b)

# b
A = np.array([[2,1,0,0],[1,2,1,0],[0,1,2,1],[0,0,1,2]])
x = np.array([1,1,1,2])

b = A.dot(x)
print(b)

[18  5  0]
[3 4 5 5]


### 23

In [20]:
A = np.array([[1,2],[3,4]])
x = np.array([5,-2])
b = np.array([1,7])

# checking each element, and whether all of them are true.
print((np.dot(A,x) == b).all())

True


### 24

In [49]:
A = np.eye(3)
v = np.array(range(3,6))

print(A.dot(v))
print(v.dot(v.T))

[3. 4. 5.]
50


### 25

In [67]:
A = np.ones((4,4))
v = np.ones((4,1))
print(A.dot(v).T)

B = np.eye(4) + np.ones(4)
w = np.zeros((4,1)) + 2*np.ones((4,1))
print(B.dot(w).T)

[[4. 4. 4. 4.]]
[[10. 10. 10. 10.]]


### 29

In [77]:
A = np.array([[.8,.3],[.2,.7]])
u0 = np.array([1,0])

u = u0
for i in range(1,8):
    u = A.dot(u)
    print("u"+str(i)+":",u)
    
# steady state vector [0.6, 0.4]

u1: [0.8 0.2]
u2: [0.7 0.3]
u3: [0.65 0.35]
u4: [0.625 0.375]
u5: [0.6125 0.3875]
u6: [0.60625 0.39375]
u7: [0.603125 0.396875]


### 34

In [80]:
A = np.array([[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]])
b = np.array([1,2,3,4])

x = solve(A,b)
print(x)

[4. 7. 8. 6.]
