In [2]:
import numpy as np
from scipy.linalg import solve

### №1

In [3]:
#column vectors
s1,s2,s3 = [1,1,1],[0,1,1],[0,0,1]

S = np.array([s1,s2,s3]).T
x = np.array([3,4,5])

b = np.dot(S,x)
print(b)

[ 3  7 12]


### №2

In [4]:
s1,s2,s3 = [1,1,1],[0,1,1],[0,0,1]
S = np.array([s1,s2,s3]).T
b1 = np.array([1,1,1])
b2 = np.array([1,4,9])

x1 = solve(S,b1)
print(x)
x2 = solve(S,b2)
print(x2)

#test
print(np.allclose(np.dot(S, x1), b1), np.allclose(np.dot(S, x2), b2))

[3 4 5]
[1. 3. 5.]
True True


### №3

In [5]:
s1,s2,s3 = [1,1,1],[0,1,1],[0,0,1]
S = np.array([s1,s2,s3]).T
S_inv = np.linalg.inv(S)
print(S_inv)

[[ 1.  0.  0.]
 [-1.  1.  0.]
 [ 0. -1.  1.]]


*Inverse Matrix exist, columns are independent*

### №4

In [11]:
w1,w2,w3 = [1,2,3],[4,5,6],[7,8,9]
W = np.array([w1,w2,w3]).T
b = [0,0,0]

#prints error, x is singular
x = solve(W,b)

LinAlgError: Matrix is singular.

### №5

In [15]:
r1,r2,r3 = [1,4,7],[2,5,8],[3,6,9]
W = np.array([r1,r2,r3]).T
b = np.array([0,0,0])

print(W)
y = solve(W,b)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0.  0. -0.]


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  


### №6

* *c = 3*
* *c = -1*
* *independent for c != 0*

### №7

*Because each row and x dot multiplication equals 0*  
*If all they lie on the same plane, then whole plane is perpendicular to x*  

### №8

In [16]:
a1,a2,a3,a4 = [1,-1,0,0],[0,1,-1,0],[0,0,1,-1],[0,0,0,1]
A = np.array([a1,a2,a3,a4]).T
A_inv = np.linalg.inv(A)
print(A_inv)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


### №9

*Cyclic 3d hyberplane*  
[1,0,0,-1]   
[-1,1,0,0]  
[0,-1,1,0]  
[0,0,-1,1]  

### №10

In [19]:
a1,a2,a3 = [-1,0,0],[1,-1,0],[0,1,-1]
A = np.array([a1,a2,a3]).T
A_inv = np.linalg.inv(A)
print(A_inv)

[[-1. -1. -1.]
 [-0. -1. -1.]
 [-0. -0. -1.]]


### №12

In [24]:
a1,a2,a3,a4 = [0,-1,0,0],[1,0,-1,0],[0,1,0,-1],[0,0,1,0]
A = np.array([a1,a2,a3,a4]).T
A_inv = np.linalg.inv(A)
print(A_inv)

[[-0. -1. -0. -1.]
 [ 1.  0.  0.  0.]
 [-0. -0. -0. -1.]
 [ 1.  0.  1.  0.]]
